### ISSUE TITLE
Errors trying to build libarpack

### ISSUE THREAD

**Issue by ajos6183** [wo80/vs-arpack#4]
Hi @wo80,

While trying to build libarpack, i am getting the following errors:
![image](https://user-images.githubusercontent.com/32379403/84980821-6eb78680-b176-11ea-8aab-865a132622c4.png)
Do you have any idea as to what might be causing this?

**Comment by wo80** [comment]
That's strange. I compiled the project a few days ago with VS 2019 and everything worked as expected. Which compiler do you use?

The `debug_` symbol is defined in `src\ARPACK\arpack-ng\common_blocks.h`, but the header is guarded with `#pragma once`. And I cannot find `MemoryOverflow` anywhere?

Must be something with your configuration. Which libraries are you importing (blas, lapack) and how were they built?

**Comment by ajos6183** [comment]
I tried using the pre-built libraries you had put up as well as building my own ones, but the outcome was the same. I am using v142 of the C++ build tools. I have attached my libs folder if that helps. [libs.zip](https://github.com/wo80/vs-arpack/files/4796722/libs.zip)

**Comment by wo80** [comment]
I just recompiled with the libraries you provided. No problem there. Have you changed anything in the project configuration? Do you have any idea, where the `MemoryOverflow` symbol comes from?

**Comment by ajos6183** [comment]
No i haven't changes anything, and no idea about the `MemoryOverflow` error. I tried deleting all the `ar_xi_exports` files except one and that was built successfully. So the error seems to be with the `_debug` parameter. But if it is working on your system, maybe it's just something strange happening on my machine.

**Comment by wo80** [comment]
I've pushed the latest changes (switch to platform toolset v142) and updated the binaries on http://wo80.bplaced.net/math/packages.html.

**Comment by ajos6183** [comment]
Thank you, i tried your new solution but i am still getting the same errors. It seems like it's a local problem. I will just use your binaries and close this issue.
